# -------------------------------------------------------------------------------------------------
# This GitHub Actions workflow will open a PR with an up-to-date changelog and README.
# The PR can be merged manually at any time which will trigger a new release.
#
# This file has been initially created for https://github.com/politician/template-terraform
#
# Copyright 2022 Romain Barissat. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -------------------------------------------------------------------------------------------------
---
name: release

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate app token
        id: generate_token
        # yamllint disable-line rule:line-length
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ secrets.GH_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          permissions: contents:write, pull_requests:write
          # Uncomment if the app is installed at the organization level
          # organization: ${{ github.repository_owner }}

      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: terraform-module
          package-name: ${{ github.event.repository.name }}
          token: ${{ steps.generate_token.outputs.token }}
